### ISSUE TITLE
Add the ability to give characters light sources other than Darkvision

### ISSUE THREAD

**Issue by StumbleRunner** [Durtur/Dungeoneer#46]
Apologies if this exists and I haven't figured out how to use it. 

Add the ability to give non-darkvision characters a torch or have a light spell cast on them. 

I tried playing with the group and just giving the ndv folks a darkvision radius appropriate to the effect/item but the problem that came up was that everyone should be able to see that light source and so it didn't work out really well on the map for deciding who could really see what opponents in a cavern fight

**Comment by Durtur** [comment]
Hi. You can place a light effect directly on the character token, and it will move with the token. If you don't like the animations on the light effect you can create your own transparent one in the effect add window (The + button in the map tool). Please let me know if this solves your problem :)

**Comment by StumbleRunner** [comment]
That did solve the problem, my thanks. My mistake was thinking that effects were fixed to locations. Is there a wiki or user documentation that has this info?

**Comment by StumbleRunner** [comment]
A bit of a caveat on that last post. If you toggle "show visibility layer" on and off, any added light effects seem to disappear.

**Comment by Durtur** [comment]
I did get some documentation started in the about window, but I haven't updated it in a while, and I haven't gotten around to documenting the map window functionality, since I'm still adding to it.  

Regarding the visibility layer, it's intentional that the effects disappear, although they still provide light. The idea was to emulate lighting that isn't visible as effect, such as the sun shining into a cave opening or windows. That feature would also require some documentation.

**Comment by Durtur** [comment]
I'm assuming that the issue is resolved, feel free to open a new issue if not :)
