### ISSUE TITLE
[BUG] Broken thumbnails in default map library

### ISSUE THREAD

**Issue by 0x07C0** [Durtur/Dungeoneer#73]
**Describe the bug**
Client is unable to find map thumbnails when listing available maps.

**Expected behavior**
Thumbnail is loaded and displays `map` or `foregroundBase64` extracted from `.dungeoneer_map` json file.

**Screenshots**
![image](https://user-images.githubusercontent.com/37380849/184475024-955418a8-a733-4ec8-a9b8-6363fbc47a33.png)

**Additional context**
Console output:
```
Failed to load resource: net::ERR_FILE_NOT_FOUND 
~/.config/Dungeoneer/data/maptool_libraries/Default/thumbnails/roadside%20waterfall.dungeoneer_map.png
```
for every map available.

`~/.config/Dungeoneer/data/maptool_libraries/Default/thumbnails/` exists, but is empty.

**Comment by 0x07C0** [comment]
Might be a linux-only issue. Is linux still being supported?

**Comment by Durtur** [comment]
@0x07C0  it's a Linux issue, I created a Linux build a few versions ago but haven't done so recently. This is due to the Sharp image library package that was crashing the renderer process on Linux. The package isn't included if the program is runnning on Linux (dataaccess.js line 32).  Since later versions rely heavily on Sharp this should be fixed. 

There have been a few sharp realeses and Electron releases so maybe it works if the condition is removed

**Comment by 0x07C0** [comment]
Removing the condition does fix the issue, but require the deletion of old `library_data.json` in `~/.config/Dungeoneer/data/maptool_libraries/Default/`
I don't know about any bugs this will create, but sharp package does work on linux without breaking any features.

**Comment by Durtur** [comment]
Nice. It shouldn't create any bugs. The issue was that the map tool window did not open, it showed only a white screen without even devtools available.

**Comment by 0x07C0** [comment]
Does that mean that the restriction on [dataaccess.js#L359](https://github.com/Durtur/Dungeoneer/blob/master/app/js/dataaccess.js#L359) is also redundant?

**Comment by Durtur** [comment]
Yes it's not needed
