### ISSUE TITLE
[BUG] Hosting Playerside Map and UI Problem

### ISSUE THREAD

**Issue by YasinAhmet** [Durtur/Dungeoneer#87]
**Describe the bug**
Playerside is not able to see the map. UI doesn't work correctly. You can see the details on the image, I just connected to myself from the invite link to test the dynamical fog mechanics, but it seems like I am not going to see the map soon.

**Expected behavior**
It has to show me the map from the playerside, give the player a token etc. 

**Screenshots**
![image](https://user-images.githubusercontent.com/77017655/196436945-1505bfce-6df4-4b96-9100-f49bfb06ade3.png)

+ I have tried it on Opera GX and Google Chrome. Both has the same problem. The image taken on Chrome.

**Comment by YasinAhmet** [comment]
I have just restarted the server, it solved the problem. But there is still a bug inside probably.

**Comment by Durtur** [comment]
Great, thanks for reporting this. 

Since the client connects directly to your machine with peer to peer it is possible that data transfers fail, especially if the map is changed whilst the transfer is ongoing, in which case the client needs to reconnect. It's on the todo list to make it a little bit more robust. If it happens again, feel free to reopen this issue. It would also be helpful to get a screenshot from the devtools console in the server window (ctrl shift i opens it)
