### ISSUE TITLE
[Feature] Allow usage of Gifs as tokens

### ISSUE THREAD

**Issue by alcros33** [Durtur/Dungeoneer#95]
**Description**
As of right now the app converts automatically any image selected as token to webp. This can be changed by manually copying the gif image to the maptool_tokens folder and renaming it to match the ID allowing the usage of gifs in the app itself. However, when the server sends images to the client it first converts it to svg or webp only making it so the clients cannot see the animation.

**Proposed solution**
Remove the manual conversion to webp and svg added in the `toBase64` in the `server.util.js` file. And add a request parameter for the format in the server notification of the token-image (Probably in the `onBackgroundChanged` function in the `map.admin.js`).
Also add a format parameter in the case for "token-image" at the `setState` function in the `` `client.js` file.

**Comment by Durtur** [comment]
Sounds correct, but I think the webp conversion should be kept since it reduces the payload size by alot. The toBase64 method could support svg or gif. Any other format should just be changed to webp. If the dataAccess.commitTokenSave method is tweaked so it saves gif as actual gifs instead of webp that should be enough to support gifs. 

You're welcome to create PR if you'd like otherwise I can probably take a look at this during the weekend.

**Comment by alcros33** [comment]
maybe I can give it a shot, but how exactly do I host the client part? The one hosted at [https://www.ogreforge.me/Dungeoneer/client](https://www.ogreforge.me/Dungeoneer/client) given that the run_server.py seems to be empty

**Comment by Durtur** [comment]
It's just a static site under the /docs folder so any hosting option would do, probably the easiest being python http.server (https://pythonbasics.org/webserver/)
